### ISSUE TITLE
Tipped Arrow Crash - MC 1.10

### ISSUE THREAD

**Issue by Peach774** [BrassGoggledCoders/ModularUtilities#1]
Just received this crash when shot by a skeleton.
http://pastebin.com/yGETdw5Q

**Comment by FreneticScribbler** [comment]
I can't see the crash log...

**Comment by Peach774** [comment]
Oops, Yeah, it didn't crash crash, it just locked up so it only generated in the log files. I cant find it again unfortunately. I installed the mod, got shot by a skeleton and then the game locked up. It was related to tipped arrows if that helps.

**Comment by mallrat208** [comment]
I ran into this same crash actually...
https://gist.github.com/mallrat208/516bf464c891cc8a3e8314360519f45b

Looks like [onEntityAttacked](https://github.com/BrassGoggledCoders/ModularUtilities/blob/master/src/main/java/xyz/brassgoggledcoders/modularutilities/modules/enchantments/EnchantmentsModule.java#L120) in the EnchantmentModule just needs to account for EntityTippedArrow

**Comment by FreneticScribbler** [comment]
Alrighty, should have a fix out this afternoon.

**Comment by FreneticScribbler** [comment]
Fix released.
