### ISSUE TITLE
Modular Utilities Crash

### ISSUE THREAD

**Issue by 63502** [BrassGoggledCoders/ModularUtilities#8]
I do not know what this is, but it happens whenever MoU is in the same folder as the latest BASE
.
[Crash Log w/ extra mods](https://gist.github.com/63502/d25033f3ea7b5e6f92ba21786830ff2c)

Also see [BASE issue #38](https://github.com/The-Acronym-Coders/BASE/issues/38)

**Comment by SkySom** [comment]
It looks like I broke way more in MoU than expected. Will have to fix tomorrow. BASE 1.1 should be fine for all mods dependent on BASE still though.

**Comment by 63502** [comment]
Ok, thanks for looking into it. :)

**Comment by SkySom** [comment]
Turns out I lied, it was all in BASE abstractions. Everything should be fixed now.
